### ISSUE TITLE
Could not load Cake.XdtTransform.dll (missing DotNet.Xdt)

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Sitecore.Demo.Headless#102]
Encountered this error attempting to run `build.ps1`. See full error below. Found similar issue here:
cake-contrib/Cake.XdtTransform#34

Workaround is to change `#addin` for `Cake.XdtTransform` to:

```
#addin nuget:?package=Cake.XdtTransform&version=0.18.0&loaddependencies=true
```

### Full error
```
PS server> .\build.ps1
Preparing to run build script...
Running build script...
Could not load C:\dev\Sitecore.HabitatHome.Omni\fitness\server\tools\Addins\Cake.XdtTransform.0.18.1\lib\netstandard2.0\Cake.XdtTransform.dll (missing DotNet.Xdt, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null)
(2699,12): warning CS1701: Assuming assembly reference 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' used by 'Cake.Json' matches identity 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' of 'Newtonsoft.Json', you may need to supply runtime policy
(2705,12): warning CS1701: Assuming assembly reference 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' used by 'Cake.Json' matches identity 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' of 'Newtonsoft.Json', you may need to supply runtime policy
C:/dev/Sitecore.HabitatHome.Omni/fitness/server/CakeScripts/helper-methods.cake(116,9): error CS0103: The name 'XdtTransformConfig' does not exist in the current context
Error: Error(s) occurred when compiling build script:
C:/dev/Sitecore.HabitatHome.Omni/fitness/server/CakeScripts/helper-methods.cake(116,9): error CS0103: The name 'XdtTransformConfig' does not exist in the current context
```

**Comment by jeanfrancoislarente** [comment]
Thanks @nickwesselman 

We've fixed it internally and are in the process of merging and pushing to GitHub (likely this week or early next week).

We resolved the issue by pinning the version but will look at the &loaddependencies=true flag before we push!
FYI @jflheureux

**Comment by mathewevans** [comment]
I am having this issue where the DotNet.Xdt.Resouce cannot be found

But the strange thing it is only happening on one local development machine
The other Dev machine is quite happy to build and deploy the app locally so i guess it must be an environment issue but i dont know where to start


Resolving assembly DotNet.Xdt.resources, Version=2.1.1.0, Culture=en-US, PublicKeyToken=null
Exception while resolving assembly DotNet.Xdt.resources: Could not load file or assembly 'DotNet.Xdt.resources' or one of its dependencies. The system cannot find the file specified.
An error occurred when executing task 'Apply-Xml-Transform'.
Error: System.AggregateException: One or more errors occurred. ---> DotNet.Xdt.XmlNodeException: No element in the source document matches '/configuration/appSettings/add[@key='env:define']'
   at DotNet.Xdt.XmlTransformationLogger.LogErrorFromException(Exception ex)
   at DotNet.Xdt.XmlTransformation.Apply(XmlDocument xmlTarget)
   at Cake.XdtTransform.XdtTransformation.TransformConfig(FilePath sourceFile, FilePath transformFile, FilePath targetFile)

**Comment by jflheureux** [comment]
Original issue seems to be resolved now. @mathewevans if you are still experiencing an issue, please open a new one. Thanks.
