### ISSUE TITLE
Event Registration on PWA triggers MA email for Kiosk app

### ISSUE THREAD

**Issue by scottmulligan** [Sitecore/Sitecore.Demo.Headless#70]
Small ToDo - Maybe a separate "Register" goal for Kiosk and PWA so that the PWA registration does not kick off the MA plan for kiosk registration

Aha! Link: https://habitathome.aha.io/features/JSS-27

**Comment by jflheureux** [comment]
Not relevant anymore with the switch to Boxever and Moosend
