### ISSUE TITLE
Multiple event registrations not receiving email in Kiosk App

### ISSUE THREAD

**Issue by scottmulligan** [Sitecore/Sitecore.Demo.Headless#72]
When registering for an event in the Kiosk app, when a new user email is submitted it goes through the MA plan and the email is sent as expected. If that same email is used to register for another event in the Kiosk app in that session or another session then the email is never delivered. The visitor is added to the MA plan as expected but the email is never delivered.

Aha! Link: https://habitathome.aha.io/features/JSS-29

**Comment by jflheureux** [comment]
I believe this is fixed with the switch to Boxever
